### ISSUE TITLE
FastEPRR

### ISSUE THREAD

**Issue by ghost** [gaoisbest/FastEPRR#2]
hello, could you send me a   FastEPRR package（.tar.gz）, because the web URL is not valid（http://www.picb.ac.cn/evolgen）。my E-mail ：978835147@qq.com 。thank you.

**Comment by ChinJCheung** [comment]
I have the same problem, the web URL is not valid（[http://www.picb.ac.cn/evolgen）

**Comment by gaoisbest** [comment]
Sorry for late reply, please see https://www.picb.ac.cn/evolgen/softwares/index.html
