### ISSUE TITLE
Issue in FastEPRR_VCF_step2 : Error in if (currH <= zeroLow)

### ISSUE THREAD

**Issue by CamilleKessler** [gaoisbest/FastEPRR#4]
Hi, 

I'm having a problem when running the function FastEPRR_VCF_step2, the step1 function worked fine.

 I used for the step2:
 
```
FastEPRR_VCF_step2(srcFolderPath = "/home/ckessler/scratch/recombination_rate/step1", 
                     replicateNum = 100, getCI = TRUE,
                     DXOutputFolderPath = "/home/ckessler/scratch/recombination_rate/step2")

Loading required package: mboost
Loading required package: parallel
Loading required package: stabs
Total DXs in this job: 1024, current DX: 1
Curr dton: 54 xton: 290
0 0.5 1 2 5 10 20 40 70 110 170 
Error in if (currH <= zeroLow) { : missing value where TRUE/FALSE needed
Calls: FastEPRR_VCF_step2 -> lapply -> FUN -> sameConfig -> lapply -> FUN
Execution halted
```
 
Any help would be greatly appreciated.

**Comment by hzt314** [comment]
I've got the same issue, and solved by editing my step2 input files. Please check the first column of your step2 input files, the chr number should by numeric instead of character (i.e. 1 instead of 'chr1') -- those characters cannot be taken during the calculation.

**Comment by CamilleKessler** [comment]
Yes, that worked! Thank you !
